workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      node: latest
    scripts:
      - npm install
      - npx cap copy
      - npx cap sync
    artifacts:
      - ios/App/build/Release-iphoneos/App.ipa